name: atmos
on:
  push:
    branches:
      - main
jobs:
  main:
    # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@main
      # https://github.com/docker/login-action
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'build & push'
        run: |
          TAG=$(sed -n 's/^ARG AT_VER=\(.*\)/\1/p' Dockerfile)
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:$TAG
          docker push ghcr.io/$GITHUB_REPOSITORY:$TAG
